SHIPPING 에러 오타수정
LIKE 고유 명령어 -> LIKEY 로 교체
ON DELETE CASCADE추가
모든 명령어 " " 제거

--회원번호
CREATE SEQUENCE SEQ_MNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--댓글
CREATE SEQUENCE SEQ_RENO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--대댓글
CREATE SEQUENCE SEQ_RRENO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--사진
CREATE SEQUENCE SEQ_PICNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--리워드
CREATE SEQUENCE SEQ_RWNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--옵션
CREATE SEQUENCE SEQ_OPNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--메시지
CREATE SEQUENCE SEQ_MSGNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--채팅방
CREATE SEQUENCE SEQ_MRNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--프로젝트
CREATE SEQUENCE SEQ_PNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--프로젝트카테고리
CREATE SEQUENCE SEQ_PCANO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--신고
CREATE SEQUENCE SEQ_RPNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--1:1상담
CREATE SEQUENCE SEQ_CONO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--FAQ
CREATE SEQUENCE SEQ_FQNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--공지사항
CREATE SEQUENCE SEQ_NONO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--배송자
CREATE SEQUENCE SEQ_DVNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--주문정보
CREATE SEQUENCE SEQ_ODNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--결제수단
CREATE SEQUENCE SEQ_PHNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;

--은행
CREATE SEQUENCE SEQ_BKNO
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE
NOORDER;




CREATE TABLE MEMBER (
	MEMBER_NO	NUMBER		NOT NULL,
	MEMBER_EMAIL	VARCHAR2(100)		NOT NULL,
	MEMBER_PWD	VARCHAR2(100)		NOT NULL,
	MEMBER_NICKNAME	VARCHAR2(100)		NOT NULL,
	MEMBER_NAME	VARCHAR2(100)		NOT NULL,
	MEMBER_PHONE	VARCHAR2(100)		NOT NULL,
	MEMBER_CREATEDATE	DATE	DEFAULT SYSDATE	NOT NULL,
	MEMBER_GENDER	VARCHAR2(10)		NOT NULL,
	MEMBER_PF_PATH	VARCHAR2(200)		NULL,
	MEMBER_SYSTEMNAME	VARCHAR2(200)		NULL,
	MEMBER_STATUS	NUMBER	DEFAULT 1	NOT NULL,
	MEMBER_LINK	NUMBER	DEFAULT 1	NOT NULL,
	REFRES_TOKEN	VARCHAR2(100)		NULL,
	ACCESS_TOKEN	VARCHAR2(100)		NULL,
	STATUS	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호 시퀀스';

COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS '회원아이디(이메일)';

COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '비밀번호';

COMMENT ON COLUMN MEMBER.MEMBER_NICKNAME IS '회원닉네임';

COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원이름(본명)';

COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS '회원 폰번호';

COMMENT ON COLUMN MEMBER.MEMBER_CREATEDATE IS '회원 가입일';

COMMENT ON COLUMN MEMBER.MEMBER_GENDER IS '회원 성별';

COMMENT ON COLUMN MEMBER.MEMBER_PF_PATH IS '프로필 이미지 경로';

COMMENT ON COLUMN MEMBER.MEMBER_SYSTEMNAME IS '프로필  파일 시스템명';

COMMENT ON COLUMN MEMBER.MEMBER_STATUS IS '1.일반유저,  2.관리자,  3,블랙리스트.4탈퇴';

COMMENT ON COLUMN MEMBER.MEMBER_LINK IS '1.연동안된유저 2.네이버 연동 3. 구글 연동';

DROP TABLE PROJECT;

CREATE TABLE PROJECT (
	PROJECT_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	PRO_CATENO	NUMBER		NOT NULL,
	BANK_NO	NUMBER		NOT NULL,
	PROJECT_GOAL	VARCHAR2(50)		NULL,
	PROJECT_TITLE	VARCHAR2(500)		NULL,
	PROJECT_SUBTITLE	VARCHAR2(500)		NULL,
	PROJECT_GPRICE	NUMBER		NULL,
	PROJECT_START_DT	VARCHAR2(500)		NULL,
	PROJECT_CLOSE_DT	VARCHAR2(500)		NULL,
	PROJECT_URL	VARCHAR2(500)		NULL,
	PROJECT_THUMPATH	VARCHAR2(1000)		NULL,
	PROJECT_FILENAME	VARCHAR2(1000)		NULL,
	PROJECT_REASON	VARCHAR2(1000)		NULL,
	PROJECT_COUNT	NUMBER	DEFAULT 0	NOT NULL,
	PROJECT_CONTENT	CLOB		NULL,
	PROJECT_VURL	VARCHAR2(4000)		NULL,
	PROJECT_REFCON	CLOB		NULL,
	CREATOR_THUMPATH	VARCHAR2(1000)		NULL,
	CREATOR_PROFILE	VARCHAR2(1000)		NULL,
	CREATOR_NAME	VARCHAR2(300)		NULL,
	CREATOR_INTRO	VARCHAR2(4000)		NULL,
	CREATOR_PHONE	VARCHAR2(300)		NULL,
	PHONE_CHECK	VARCHAR2(3)		NULL,
	CREATOR_EMAIL	VARCHAR2(400)		NULL,
	CREATOR_BANK	VARCHAR2(100)		NULL,
	CREATOR_ACOUNT	VARCHAR2(300)		NULL,
	CREATOR_ACHOLDER	VARCHAR2(500)		NULL,
	CREATOR_WEBURL	VARCHAR2(4000)		NULL,
	CREATOR_INSTA	VARCHAR2(4000)		NULL,
	CREATOR_FACEBOOK	VARCHAR2(4000)		NULL,
	CREATOR_STATUS	VARCHAR2(1)		NULL,
	HASHTAG	VARCHAR2(1000)		NULL,
	PROJECT_CRDATE	DATE	DEFAULT SYSDATE	NOT NULL,
	PROJECT_TEMPORARY	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN PROJECT.PROJECT_NO IS '프로젝트 식별자';

COMMENT ON COLUMN PROJECT.MEMBER_NO IS '회원번호 시퀀스';

COMMENT ON COLUMN PROJECT.PRO_CATENO IS '식별자';

COMMENT ON COLUMN PROJECT.BANK_NO IS '은행식별자';

COMMENT ON COLUMN PROJECT.PROJECT_GOAL IS 'Y. 100% 일때 완료 N조건없음';

COMMENT ON COLUMN PROJECT.PROJECT_TITLE IS '프로젝트 제목';

COMMENT ON COLUMN PROJECT.PROJECT_SUBTITLE IS '프로젝트 부제목';

COMMENT ON COLUMN PROJECT.PROJECT_GPRICE IS '목표금액';

COMMENT ON COLUMN PROJECT.PROJECT_START_DT IS '프로젝트 시작일';

COMMENT ON COLUMN PROJECT.PROJECT_CLOSE_DT IS '프로젝트 데드라인';

COMMENT ON COLUMN PROJECT.PROJECT_URL IS '프로젝트 URL';

COMMENT ON COLUMN PROJECT.PROJECT_THUMPATH IS '프로젝트 썸네일 패스';

COMMENT ON COLUMN PROJECT.PROJECT_FILENAME IS '프로젝트 썸네일파일명';

COMMENT ON COLUMN PROJECT.PROJECT_REASON IS '취소반려사유';

COMMENT ON COLUMN PROJECT.PROJECT_COUNT IS '조회수';

COMMENT ON COLUMN PROJECT.PROJECT_CONTENT IS '프로젝트 스토리(CKEditor)';

COMMENT ON COLUMN PROJECT.PROJECT_VURL IS '동영상 URL';

COMMENT ON COLUMN PROJECT.PROJECT_REFCON IS '교환환불정책';

COMMENT ON COLUMN PROJECT.CREATOR_THUMPATH IS '크리에이터 프로필';

COMMENT ON COLUMN PROJECT.CREATOR_PROFILE IS '크리에이어 프로필 파일명';

COMMENT ON COLUMN PROJECT.CREATOR_NAME IS '크리에이터 이름';

COMMENT ON COLUMN PROJECT.CREATOR_INTRO IS '크리에이터 소개';

COMMENT ON COLUMN PROJECT.CREATOR_PHONE IS '문의 가능번호';

COMMENT ON COLUMN PROJECT.PHONE_CHECK IS '문의번호 공개여부';

COMMENT ON COLUMN PROJECT.CREATOR_EMAIL IS '문의 이메일';

COMMENT ON COLUMN PROJECT.CREATOR_BANK IS '거래은행';

COMMENT ON COLUMN PROJECT.CREATOR_ACOUNT IS '계좌번호';

COMMENT ON COLUMN PROJECT.CREATOR_ACHOLDER IS '예금주명';

COMMENT ON COLUMN PROJECT.CREATOR_WEBURL IS 'WEB SNS 주소(개인 웹사이트)';

COMMENT ON COLUMN PROJECT.CREATOR_INSTA IS '인스타 공유주소';

COMMENT ON COLUMN PROJECT.CREATOR_FACEBOOK IS '페이스북 공유주소';

COMMENT ON COLUMN PROJECT.CREATOR_STATUS IS 'R.수락요청 B.블라인드 U.게시중 D. 반려 T.임시저장';

COMMENT ON COLUMN PROJECT.HASHTAG IS '해시테그';

COMMENT ON COLUMN PROJECT.PROJECT_CRDATE IS '프로젝트 등록일(승인요청 누른날짜)';

COMMENT ON COLUMN PROJECT.PROJECT_TEMPORARY IS '프로젝트 임시저장';

DROP TABLE NOTICE;

CREATE TABLE NOTICE (
	NOTICE_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	NOTICE_TITLE	VARCHAR2(200)		NOT NULL,
	NOTICE_CONTENT	CLOB		NOT NULL,
	NOTICE_UPLOAD	DATE	DEFAULT SYSDATE	NOT NULL,
	NOTICE_COUNT	NUMBER	DEFAULT 0	NOT NULL,
	NOTICE_STATUS	VARCHAR2(200)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지사항 식별자';

COMMENT ON COLUMN NOTICE.MEMBER_NO IS '회원번호 시퀀스';

COMMENT ON COLUMN NOTICE.NOTICE_COUNT IS '조회수';

COMMENT ON COLUMN NOTICE.NOTICE_STATUS IS 'N.삭제 Y.공지중';

DROP TABLE PRO_CATEGORY;

CREATE TABLE PRO_CATEGORY (
	PRO_CATENO	NUMBER		NOT NULL,
	PRO_CATENAME	VARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN PRO_CATEGORY.PRO_CATENO IS '식별자';

COMMENT ON COLUMN PRO_CATEGORY.PRO_CATENAME IS '카테고리명';

DROP TABLE SHIPPPING;

CREATE TABLE SHIPPPING (
	SHIPPING_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	SHIPPING_ZIPCODE	VARCHAR2(30)		NULL,
	SHPPING_D_ADDR	VARCHAR2(400)		NULL,
	SHIPPING_S_ADDR VARCHAR2(400)		NULL,
	RECEIEVER_NAME	VARCHAR2(100)		NULL,
	RECEIEVER_PHONE	VARCHAR2(100)		NULL,
	SHHIPING_BASIC	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN SHIPPPING.SHIPPING_NO IS '배송지 식별자';

COMMENT ON COLUMN SHIPPPING.MEMBER_NO IS '회원번호 시퀀스';

COMMENT ON COLUMN SHIPPPING.SHIPPING_ZIPCODE IS '우편번호';

COMMENT ON COLUMN SHIPPPING.SHPPING_D_ADDR IS '회원 상세주소';

COMMENT ON COLUMN SHIPPPING.SHIPPING_S_ADDR IS '일반주소';

COMMENT ON COLUMN SHIPPPING.RECEIEVER_NAME IS '수취인명';

COMMENT ON COLUMN SHIPPPING.RECEIEVER_PHONE IS '수취인번호';

COMMENT ON COLUMN SHIPPPING.SHHIPING_BASIC IS '기본배송지';

DROP TABLE MEMBER_PURCHASE;

CREATE TABLE MEMBER_PURCHASE (
	PURCHASE_NO	VARCHAR2(100)		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	PURCHASE_C_NUMBER	VARCHAR2(100)		NULL,
	PURCHASE_V_YEAR	VARCHAR2(100)		NULL,
	PURCHASE_V_MONTH	VARCHAR2(100)		NULL,
	PURCHASE_C_PWD	VARCHAR2(100)		NULL,
	PURCHASE_C_DATE	VARCHAR2(100)		NULL,
	PURCHASE_BKEY	VARCHAR2(300)		NULL,
	PURCHASE_EMAIL	VARCHAR2(100)		NULL,
	PURCHASE_BASIC	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN MEMBER_PURCHASE.PURCHASE_NO IS '결제수단식별자';

COMMENT ON COLUMN MEMBER_PURCHASE.MEMBER_NO IS '회원번호 시퀀스';

COMMENT ON COLUMN MEMBER_PURCHASE.PURCHASE_C_NUMBER IS '카드번호';

COMMENT ON COLUMN MEMBER_PURCHASE.PURCHASE_V_YEAR IS '카드유효기간년도';

COMMENT ON COLUMN MEMBER_PURCHASE.PURCHASE_V_MONTH IS '카드유효기간월';

COMMENT ON COLUMN MEMBER_PURCHASE.PURCHASE_C_PWD IS '카드비밀번호';

COMMENT ON COLUMN MEMBER_PURCHASE.PURCHASE_C_DATE IS '생년월일';

COMMENT ON COLUMN MEMBER_PURCHASE.PURCHASE_BKEY IS '회원 구매키';

COMMENT ON COLUMN MEMBER_PURCHASE.PURCHASE_EMAIL IS '회원이메일';

COMMENT ON COLUMN MEMBER_PURCHASE.PURCHASE_BASIC IS '기본결제수단';

DROP TABLE FAQ;

CREATE TABLE FAQ (
	FAQ_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	FAQ_TITLE	VARCHAR2(200)		NOT NULL,
	FAQ_CONTENT	VARCHAR2(2000)		NOT NULL,
	FAQ_STATUS	VARCHAR2(200)	DEFAULT 'Y'	NOT NULL,
	FAQ_CATE	NUMBER		NOT NULL
);

COMMENT ON COLUMN FAQ.FAQ_NO IS 'FAQ 식별자';

COMMENT ON COLUMN FAQ.MEMBER_NO IS '회원번호 시퀀스';

COMMENT ON COLUMN FAQ.FAQ_TITLE IS 'FAQ제목';

COMMENT ON COLUMN FAQ.FAQ_CONTENT IS 'FAQ내용';

COMMENT ON COLUMN FAQ.FAQ_STATUS IS 'N.삭제 Y.공지중';

COMMENT ON COLUMN FAQ.FAQ_CATE IS '1.로그인 2.크리에이터 3. 서포터';

DROP TABLE COUNCIL;

CREATE TABLE COUNCIL (
	COUNCIL_NO	NUMBER		NOT NULL,
	COUNCIL_TITLE	VARCHAR2(1000)		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	COUNCIL_CONTENT	CLOB		NOT NULL,
	COUNCIL_C_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	COUNCIL_ANS	CLOB		NULL,
	COUNCIL_STATUS	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	COUNCIL_CATE	NUMBER		NOT NULL,
	COUNCIL_A_DATE	DATE		NULL
);

COMMENT ON COLUMN COUNCIL.COUNCIL_NO IS '1:1게시판 식별자';

COMMENT ON COLUMN COUNCIL.COUNCIL_TITLE IS '게시판제목';

COMMENT ON COLUMN COUNCIL.MEMBER_NO IS '회원번호 시퀀스';

COMMENT ON COLUMN COUNCIL.COUNCIL_CONTENT IS '게시판 내용';

COMMENT ON COLUMN COUNCIL.COUNCIL_C_DATE IS '게시판 날짜';

COMMENT ON COLUMN COUNCIL.COUNCIL_ANS IS '답변내용';

COMMENT ON COLUMN COUNCIL.COUNCIL_STATUS IS 'Y.답변완료 N.미답변  D.삭제';

COMMENT ON COLUMN COUNCIL.COUNCIL_CATE IS '1.리워드 2.프로젝트 3.기타';

COMMENT ON COLUMN COUNCIL.COUNCIL_A_DATE IS '답변날짜';

DROP TABLE REWARD;

CREATE TABLE REWARD (
	RE_NO	NUMBER		NOT NULL,
	PROJECT_NO	NUMBER		NOT NULL,
	RE_PRICE	NUMBER		NULL,
	RE_STATUS	VARCHAR2(50)		NULL,
	RE_NUMBER	NUMBER		NULL,
	RE_SH_STATUS	VARCHAR2(10)		NULL,
	RE_SALECOUNT	NUMBER		NULL
);

COMMENT ON COLUMN REWARD.RE_NO IS '리워드 식별자';

COMMENT ON COLUMN REWARD.PROJECT_NO IS '프로젝트 식별자';

COMMENT ON COLUMN REWARD.RE_PRICE IS '리워드 금액';

COMMENT ON COLUMN REWARD.RE_STATUS IS 'Y제한 N무제한';

COMMENT ON COLUMN REWARD.RE_NUMBER IS '제공가능수';

COMMENT ON COLUMN REWARD.RE_SH_STATUS IS '배송지 필요여부';

COMMENT ON COLUMN REWARD.RE_SALECOUNT IS '판매갯수';

DROP TABLE CKEditor;

CREATE TABLE CKEditor (
	ED_NO	NUMBER		NOT NULL,
	PROJECT_NO	NUMBER		NULL,
	ED_FILENAME	VARCHAR2(300)		NULL,
	ED_FILEPATH	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN CKEditor.ED_NO IS '사진 식별자';

COMMENT ON COLUMN CKEditor.ED_FILENAME IS '사진 파일명';

COMMENT ON COLUMN CKEditor.ED_FILEPATH IS '사진 저장경로';

DROP TABLE RE_OPTION;

CREATE TABLE RE_OPTION (
	RE_OPTION_NO	NUMBER		NOT NULL,
	REWARD_NO	NUMBER		NOT NULL,
	RE_OPTION_NAME	VARCHAR2(80)		NULL
);

COMMENT ON COLUMN RE_OPTION.RE_OPTION_NO IS '옵션 식별자';

COMMENT ON COLUMN RE_OPTION.REWARD_NO IS '리워드 식별자';

COMMENT ON COLUMN RE_OPTION.RE_OPTION_NAME IS '옵션내용';

DROP TABLE LIKEY;

CREATE TABLE LIKEY (
	PROJECT_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL
);

COMMENT ON COLUMN LIKEY.PROJECT_NO IS '프로젝트 식별자';

COMMENT ON COLUMN LIKEY.MEMBER_NO IS '회원번호 시퀀스';

DROP TABLE REPLY;

CREATE TABLE REPLY (
	REPLY_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	PROJECT_NO	NUMBER		NOT NULL,
	REPLY_CONTENT	VARCHAR2(500)		NOT NULL,
	REPLY_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	REPLY_STATUS	VARCHAR2(5)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글식별자';

COMMENT ON COLUMN REPLY.MEMBER_NO IS '회원번호 시퀀스';

COMMENT ON COLUMN REPLY.PROJECT_NO IS '프로젝트 식별자';

COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글내용';

COMMENT ON COLUMN REPLY.REPLY_DATE IS '댓글 작성일';

COMMENT ON COLUMN REPLY.REPLY_STATUS IS 'Y.게시중 N삭제';

DROP TABLE REPLY_ANS;

CREATE TABLE REPLY_ANS (
	SUBRE_ANSNO	NUMBER		NOT NULL,
	REPLY_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	SUBRE_CONTENT	VARCHAR2(500)		NOT NULL,
	SUBRE_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	SUBRE_STATUS	VARCHAR2(5)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN REPLY_ANS.SUBRE_ANSNO IS '대댓글 식별자';

COMMENT ON COLUMN REPLY_ANS.REPLY_NO IS '댓글식별자';

COMMENT ON COLUMN REPLY_ANS.MEMBER_NO IS '회원번호 시퀀스';

COMMENT ON COLUMN REPLY_ANS.SUBRE_CONTENT IS '대댓글 내용';

COMMENT ON COLUMN REPLY_ANS.SUBRE_DATE IS '대댓글 작성일';

COMMENT ON COLUMN REPLY_ANS.SUBRE_STATUS IS 'Y.게시중 N삭제';

DROP TABLE REPORT;

CREATE TABLE REPORT (
	REPORT_NO	NUMBER		NOT NULL,
	PROJECT_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	REPORT_CONTENT	VARCHAR2(1000)		NOT NULL,
	REPORT_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	REPORT_STATUS	VARCHAR2(10)	DEFAULT 'P'	NOT NULL
);

COMMENT ON COLUMN REPORT.REPORT_NO IS '신고 식별자';

COMMENT ON COLUMN REPORT.PROJECT_NO IS '프로젝트 식별자';

COMMENT ON COLUMN REPORT.MEMBER_NO IS '회원번호 시퀀스';

COMMENT ON COLUMN REPORT.REPORT_CONTENT IS '신고내용';

COMMENT ON COLUMN REPORT.REPORT_DATE IS '신고일';

COMMENT ON COLUMN REPORT.REPORT_STATUS IS 'P.진행중 D.처리완료';

DROP TABLE MSGROOM;

CREATE TABLE MSGROOM (
	MSGROOM_NO	NUMBER		NOT NULL,
	PROJECT_NO	NUMBER		NOT NULL,
	SUP_USER_NO	NUMBER		NOT NULL,
	CRE_USER_NO	NUMBER		NOT NULL
);

COMMENT ON COLUMN MSGROOM.MSGROOM_NO IS '채팅방식별자';

COMMENT ON COLUMN MSGROOM.PROJECT_NO IS '프로젝트 식별자';

COMMENT ON COLUMN MSGROOM.SUP_USER_NO IS '회원번호 시퀀스';

COMMENT ON COLUMN MSGROOM.CRE_USER_NO IS '회원번호 시퀀스';

DROP TABLE MESSAGE;

CREATE TABLE MESSAGE (
	MSG_NO	NUMBER		NOT NULL,
	MSG_CONTENT	VARCHAR2(1000)		NOT NULL,
	MSG_SENDDATE	DATE	DEFAULT SYSDATE	NOT NULL,
	PROJECT_NO	NUMBER		NOT NULL,
	MSG_SENDER	NUMBER		NOT NULL,
	MSG_RECEIVER	NUMBER		NOT NULL,
	MSGROOM_NO	NUMBER		NOT NULL
);

COMMENT ON COLUMN MESSAGE.MSG_NO IS '메시지식별자';

COMMENT ON COLUMN MESSAGE.MSG_CONTENT IS '메시지 내용';

COMMENT ON COLUMN MESSAGE.MSG_SENDDATE IS '보낸날짜';

COMMENT ON COLUMN MESSAGE.PROJECT_NO IS '프로젝트 식별자';

COMMENT ON COLUMN MESSAGE.MSG_SENDER IS '회원번호 시퀀스';

COMMENT ON COLUMN MESSAGE.MSG_RECEIVER IS '회원번호 시퀀스';

COMMENT ON COLUMN MESSAGE.MSGROOM_NO IS '채팅방식별자';

DROP TABLE PURCHASE_INFO;

CREATE TABLE PURCHASE_INFO (
	PURINFO_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	RE_NO	NUMBER		NOT NULL,
	REWARD_AMOUNT	NUMBER	DEFAULT 0	NOT NULL,
	REWARD_PLUS	NUMBER	DEFAULT 0	NOT NULL,
	PURINFO_STATUS	VARCHAR2(5)		NOT NULL,
	DELIVERY_STATUS	VARCHAR2(200)		NULL,
	SHIPPING_ZIPCODE	VARCHAR2(30)		NULL,
	SHPPING_S_ADDR	VARCHAR2(400)		NULL,
	SHIPPING_D_ADDR	VARCHAR2(400)		NULL,
	RECEIEVER_NAME	VARCHAR2(100)		NULL,
	RECEIEVER_PHONE	VARCHAR2(100)		NULL,
	PURINFO_REQ	VARCHAR2(1000)		NULL,
	PURCHASE_C_NUMBER	VARCHAR2(100)		NULL,
	PURCHASE_V_YEAR	VARCHAR2(100)		NULL,
	PURCHASE_V_MONTH	VARCHAR2(100)		NULL,
	PURCHASE_C_PWD	VARCHAR2(100)		NULL,
	PURCHASE_C_DATE	VARCHAR2(100)		NULL,
	PURCHASE_BKEY	VARCHAR2(400)		NULL,
	PURCHASE_EMAIL	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN PURCHASE_INFO.PURINFO_NO IS '주문정보 식별자';

COMMENT ON COLUMN PURCHASE_INFO.MEMBER_NO IS '회원번호 시퀀스';

COMMENT ON COLUMN PURCHASE_INFO.RE_NO IS '리워드 식별자';

COMMENT ON COLUMN PURCHASE_INFO.REWARD_AMOUNT IS '리워드 몇개를 구매했는지 보여줌';

COMMENT ON COLUMN PURCHASE_INFO.REWARD_PLUS IS '추가후원금';

COMMENT ON COLUMN PURCHASE_INFO.PURINFO_STATUS IS 'Y 결제완료 R취소요청 F취소완료';

COMMENT ON COLUMN PURCHASE_INFO.DELIVERY_STATUS IS '배송 진행상황';

COMMENT ON COLUMN PURCHASE_INFO.SHIPPING_ZIPCODE IS '우편번호';

COMMENT ON COLUMN PURCHASE_INFO.SHPPING_S_ADDR IS '일반주소';

COMMENT ON COLUMN PURCHASE_INFO.SHIPPING_D_ADDR IS '회원 상세주소';

COMMENT ON COLUMN PURCHASE_INFO.RECEIEVER_NAME IS '수취인명';

COMMENT ON COLUMN PURCHASE_INFO.RECEIEVER_PHONE IS '수취인 핸드폰번호';

COMMENT ON COLUMN PURCHASE_INFO.PURINFO_REQ IS '배송시 요청사항';

COMMENT ON COLUMN PURCHASE_INFO.PURCHASE_C_NUMBER IS '카드번호';

COMMENT ON COLUMN PURCHASE_INFO.PURCHASE_V_YEAR IS '카드유효기간년도';

COMMENT ON COLUMN PURCHASE_INFO.PURCHASE_V_MONTH IS '카드유효기간월';

COMMENT ON COLUMN PURCHASE_INFO.PURCHASE_C_PWD IS '카드비밀번호';

COMMENT ON COLUMN PURCHASE_INFO.PURCHASE_C_DATE IS '생년월일';

COMMENT ON COLUMN PURCHASE_INFO.PURCHASE_BKEY IS '회원 구매키';

COMMENT ON COLUMN PURCHASE_INFO.PURCHASE_EMAIL IS '회원이메일';

DROP TABLE BANK;

CREATE TABLE BANK (
	BANK_NO	NUMBER		NOT NULL,
	BANK_NAME	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN BANK.BANK_NO IS '은행식별자';

COMMENT ON COLUMN BANK.BANK_NAME IS '은행이름';

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	MEMBER_NO
);

ALTER TABLE PROJECT ADD CONSTRAINT PK_PROJECT PRIMARY KEY (
	PROJECT_NO
);

ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (
	NOTICE_NO
);

ALTER TABLE PRO_CATEGORY ADD CONSTRAINT PK_PRO_CATEGORY PRIMARY KEY (
	PRO_CATENO
);

ALTER TABLE SHIPPPING ADD CONSTRAINT PK_SHIPPPING PRIMARY KEY (
	SHIPPING_NO
);

ALTER TABLE MEMBER_PURCHASE ADD CONSTRAINT PK_MEMBER_PURCHASE PRIMARY KEY (
	PURCHASE_NO
);

ALTER TABLE FAQ ADD CONSTRAINT PK_FAQ PRIMARY KEY (
	FAQ_NO
);

ALTER TABLE COUNCIL ADD CONSTRAINT PK_COUNCIL PRIMARY KEY (
	COUNCIL_NO
);

ALTER TABLE REWARD ADD CONSTRAINT PK_REWARD PRIMARY KEY (
	RE_NO
);

ALTER TABLE CKEDITOR ADD CONSTRAINT PK_CKEDITOR PRIMARY KEY (
	ED_NO
);

ALTER TABLE RE_OPTION ADD CONSTRAINT PK_RE_OPTION PRIMARY KEY (
	RE_OPTION_NO
);

ALTER TABLE LIKEY ADD CONSTRAINT PK_LIKEY PRIMARY KEY (
	PROJECT_NO,
	MEMBER_NO
);

ALTER TABLE REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY (
	REPLY_NO
);

ALTER TABLE REPLY_ANS ADD CONSTRAINT PK_REPLY_ANS PRIMARY KEY (
	SUBRE_ANSNO
);

ALTER TABLE REPORT ADD CONSTRAINT PK_REPORT PRIMARY KEY (
	REPORT_NO
);

ALTER TABLE MSGROOM ADD CONSTRAINT PK_MSGROOM PRIMARY KEY (
	MSGROOM_NO
);

ALTER TABLE MESSAGE ADD CONSTRAINT PK_MESSAGE PRIMARY KEY (
	MSG_NO
);

ALTER TABLE PURCHASE_INFO ADD CONSTRAINT PK_PURCHASE_INFO PRIMARY KEY (
	PURINFO_NO
);

ALTER TABLE BANK ADD CONSTRAINT PK_BANK PRIMARY KEY (
	BANK_NO
);

ALTER TABLE PROJECT ADD CONSTRAINT FK_MEMBER_TO_PROJECT_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE PROJECT ADD CONSTRAINT FK_PRO_CATEGORY_TO_PROJECT_1 FOREIGN KEY (
	PRO_CATENO
)
REFERENCES PRO_CATEGORY (
	PRO_CATENO
) ON DELETE CASCADE;

ALTER TABLE PROJECT ADD CONSTRAINT FK_BANK_TO_PROJECT_1 FOREIGN KEY (
	BANK_NO
)
REFERENCES BANK (
	BANK_NO
) ON DELETE CASCADE;

ALTER TABLE NOTICE ADD CONSTRAINT FK_MEMBER_TO_NOTICE_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE SHIPPPING ADD CONSTRAINT FK_MEMBER_TO_SHIPPPING_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE MEMBER_PURCHASE ADD CONSTRAINT FK_MEMBER_TO_MEMBER_PURCHASE_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE FAQ ADD CONSTRAINT FK_MEMBER_TO_FAQ_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE COUNCIL ADD CONSTRAINT FK_MEMBER_TO_COUNCIL_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE REWARD ADD CONSTRAINT FK_PROJECT_TO_REWARD_1 FOREIGN KEY (
	PROJECT_NO
)
REFERENCES PROJECT (
	PROJECT_NO
) ON DELETE CASCADE;

ALTER TABLE RE_OPTION ADD CONSTRAINT FK_REWARD_TO_RE_OPTION_1 FOREIGN KEY (
	REWARD_NO
)
REFERENCES REWARD (
	RE_NO
) ON DELETE CASCADE;

ALTER TABLE LIKEY ADD CONSTRAINT FK_PROJECT_TO_LIKEY_1 FOREIGN KEY (
	PROJECT_NO
)
REFERENCES PROJECT (
	PROJECT_NO
) ON DELETE CASCADE;

ALTER TABLE LIKEY ADD CONSTRAINT FK_MEMBER_TO_LIKEY_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE REPLY ADD CONSTRAINT FK_MEMBER_TO_REPLY_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE REPLY ADD CONSTRAINT FK_PROJECT_TO_REPLY_1 FOREIGN KEY (
	PROJECT_NO
)
REFERENCES PROJECT (
	PROJECT_NO
) ON DELETE CASCADE;

ALTER TABLE REPLY_ANS ADD CONSTRAINT FK_REPLY_TO_REPLY_ANS_1 FOREIGN KEY (
	REPLY_NO
)
REFERENCES REPLY (
	REPLY_NO
) ON DELETE CASCADE;

ALTER TABLE REPLY_ANS ADD CONSTRAINT FK_MEMBER_TO_REPLY_ANS_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE REPORT ADD CONSTRAINT FK_PROJECT_TO_REPORT_1 FOREIGN KEY (
	PROJECT_NO
)
REFERENCES PROJECT (
	PROJECT_NO
) ON DELETE CASCADE;

ALTER TABLE REPORT ADD CONSTRAINT FK_MEMBER_TO_REPORT_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE MSGROOM ADD CONSTRAINT FK_PROJECT_TO_MSGROOM_1 FOREIGN KEY (
	PROJECT_NO
)
REFERENCES PROJECT (
	PROJECT_NO
) ON DELETE CASCADE;

ALTER TABLE MSGROOM ADD CONSTRAINT FK_MEMBER_TO_MSGROOM_1 FOREIGN KEY (
	SUP_USER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE MSGROOM ADD CONSTRAINT FK_MEMBER_TO_MSGROOM_2 FOREIGN KEY (
	CRE_USER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE MESSAGE ADD CONSTRAINT FK_PROJECT_TO_MESSAGE_1 FOREIGN KEY (
	PROJECT_NO
)
REFERENCES PROJECT (
	PROJECT_NO
) ON DELETE CASCADE;

ALTER TABLE MESSAGE ADD CONSTRAINT FK_MEMBER_TO_MESSAGE_1 FOREIGN KEY (
	MSG_SENDER
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE MESSAGE ADD CONSTRAINT FK_MEMBER_TO_MESSAGE_2 FOREIGN KEY (
	MSG_RECEIVER
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE MESSAGE ADD CONSTRAINT FK_MSGROOM_TO_MESSAGE_1 FOREIGN KEY (
	MSGROOM_NO
)
REFERENCES MSGROOM (
	MSGROOM_NO
) ON DELETE CASCADE;

ALTER TABLE PURCHASE_INFO ADD CONSTRAINT FK_MEMBER_TO_PURCHASE_INFO_1 FOREIGN KEY (
	MEMBER_NO
)
REFERENCES MEMBER (
	MEMBER_NO
) ON DELETE CASCADE;

ALTER TABLE PURCHASE_INFO ADD CONSTRAINT FK_REWARD_TO_PURCHASE_INFO_1 FOREIGN KEY (
	RE_NO
)
REFERENCES REWARD (
	RE_NO
) ON DELETE CASCADE;


